### ISSUE TITLE
It's slightly off, accumulating over distance (and off-by-one somewhere I guess)

### ISSUE THREAD

**Issue by georgehank** [jonatkins/RadarGridGuide#2]
I first ignored the off-by-one (radar could be placed one outside the markings in the spot next to the root radar).

But I just noticed that at the very other end of the (by now rather large-ish :D) map, it was completely off, so these off-by-ones accumulated, such that far enough away the radar, not to overlap, must be placed outside the markers.

Damn.  I just started using it.  First I thought it wasn't really useful anymore with the radar coverage outlines on the minimap.  But if you extend a long line of radars to the side, somewhere in the middle, it is... or would be... sweet.

**Comment by jonatkins** [comment]
Sounds like you're using modded radars? If so, have you configured this mod to work with them?

To quote https://mods.factorio.com/mods/jonatkins/RadarGridGuide

> To reposition the guide marks to match an existing radar setup, or reconfigure for a modded radar with non-standard range, hover the mouse cursor over a radar and press Control+G

**Comment by georgehank** [comment]
Damn, Additional Turrets has a mod on radars.  Wasn't aware of that.  But... it only makes its howitzers be radars, it doesn't, afaict, change the base radars.  But game shows the base radars modified.  Weird.

I did, however, set the grid using ctrl-g with Additional Turrent active.

Tried w/o Additional Turrets, and the markers are correct.  Mostly.  I'd prefer them such that the radar, must always be completely inside the markers, but you can go one tile outside and it's still in a proper spot... but that's another topic.

Oh, of course that might still be due to modding... but I really can't play without SqueakThrough ;-)
